### ISSUE TITLE
lut3d

### ISSUE THREAD

**Issue by ValdikSS** [so-rose/fast-hdr#2]
As ffmpeg supports passing LUTs with `lut3d` filter, would it be possible to use said filter without any hacks?

**Comment by so-rose** [comment]
The short answer is is, no, and that it doesn't matter!



Now, for the long answer.

I'll start by saying, if you're serious about tonemapping big files in real time, use hardware acceleration. Jellyfin 10.8 now supports complete hardware accelerated HEVC decoding + filtering, including tonemapping. Many Intel CPUs have some support for this kind of thing, so you may not need a GPU. I'm pretty certain this is all ffmepg based under the hood. Clearly the way to go.

With that said, yes, lut3d does support up to 64x64x64 3D LUTs. Last I tested it, it is not very fast on CPU (CPU interpolation of 3D LUT colors, yikes), and I'm unsure if it has a GPU implementation. Even if it did, you're better off with Jellyfin's solution. Moreover, at some point you're going to have to pass an extra parameter (lut3d and lut1d) to ffmpeg based on whether or not the file is HDR, yourself - which means, yes, hacks. Either a modified ffmpeg or a modified jellyfin.

It's not a very good solution, alone. Your shadows are going to look mighty chopped up: Global HDR->SDR conversion (the type where each pixel runs the same function) fundamentally involves a color space transformation and a transfer curve. The issue with a 3D LUT alone for that purpose is the low resolution of transfer curve transforms in shadow regions. Human tonal perception is logarithmic, thus the needed resolution to satisfyingly change the transfer function in shadows is rather high - which is why 1D LUTs with 4096 points exist, and why 64 points of resolution on the luminance axis doesn't cut it. So you'd also need a lut1d filter, further stealing performance.



fast-hdr "solves" this issue, fast enough to be realtime without a lot of optimization on two standard server CPUs from 2014, via shameless precomputation.
- Take every single 8-bit color, in a majestic 256x256x256 uint8 array.
- Apply whatever transforms you need. YUV --> RGB, Colorspace Transform, Tonemapping, RGB --> YUV.
- Save it as a "LUTD8". It only spends about 16.7MB.
- Load YUV images from stdin, one by one, and index every single pixel in the LUTD8 to find its replacement. Simple lookup is one of the absolute fastest operations you can possibly perform.

As for possible optimizations:
- The bottleneck seems to be CPU HEVC decoding, which is fighting fast-hdr for CPU cycles. At good quality 4K without a CPU, the computational demands of HEVC decoding seem to be prohibitive; this is true with or without fast-hdr. You could get a GPU with HEVC decoding, but then you can probably just do GPU hardware acceleration anyway.
- If you had a theoretical 10-bit integer with optimized lookup, you could keep a precomputed 10-bit LUTD in just over a single GB of RAM. If you vectorized and micro optimized fast-hdr, and found a fast way of decoding HEVC frames (and had the bandwidth for less agressive H.264 encoding) you might be able to tonemap 4k on a couple modern higher end server CPUs doing nothing else.
