### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by dikonov** [so-rose/fast-hdr#3]
Here is the complete log of the python wrapper execution:

$ ./ffmpeg
Traceback (most recent call last):
  File "/home/slava/Загрузки/HDR/fast-hdr-master/dist/./ffmpeg.py", line 116, in <module>
    file_src = next(snip[5:] for snip in cmd_raw if snip[:5] == 'file:')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

It is also unclear, why would one need a standalone ffmpeg build, when there is ffmpeg already installed in the system (with all codecs).

**Comment by so-rose** [comment]
Hi @dikonov,

Thanks for giving it a go!

First of all, keep in mind that the python wrapper is extremely, well. _Janky_. It was very much a hack put together in a few hours, designed pretty much specifically and solely to run the following command (identical to that invoked by Jellyfin, at least back when I wrote this; see the test script in `README.md`):

```bash
"$FFMPEG_PY" -ss "$TIME" -f mp4 -i file:"$FILE" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 34541128 -bufsize 69082256 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -g 72 -keyint_min 72 -sc_threshold 0 -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -start_at_zero -vsync -1 -codec:a:0 aac -strict experimental -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "$HLS_SEG" -hls_playlist_type vod -hls_list_size 0 -y "$FILE_OUT"
```

Secondly, you absolutely do not need a standalone ffmpeg build. You simply need to adjust the constants in the file `ffmpeg` (https://github.com/so-rose/fast-hdr/blob/73cbcae2c9e98f18c17c209cbc0efffe60f2d2ee/src/ffmpeg) (it's a Python file, I promise; even though it doesn't have the `.py` extension):

```python
SCRIPT_PATH = os.path.dirname( os.path.realpath(__file__) )

MAX_WIDTH = 1920
MAX_HEIGHT = 1080

# Set Paths based
log_path = f'{SCRIPT_PATH}/hdr_sdr.log'

ffmpeg = f'{SCRIPT_PATH}/ffmpeg-custom'  ## <-- WHATEVER PATH TO YOUR FFMPEG YOU WANT
hdr_sdr = f'{SCRIPT_PATH}/hdr_sdr'
lut_path = f'{SCRIPT_PATH}/cnv.lut8'

# Assemble Basic Output Command
cmd_raw = [ffmpeg] + sys.argv[1:]
```

# How to Fix?
Well, **don't run `ffmpeg` without arguments**. Instead, try modifying the command I gave above (you should be able to remove things without consequences). And keep in mind that the wrapper is extremely imperfect (indeed, I'm currently cringing big-time at my own old code, like, who wrote this crap? :) )

Secondly, try **changing the constants to point at your system's `ffmpeg`**.

Finally, if you're interested and know Python, I can suggest trying to write (for fun) a new Python-based `ffmpeg` wrapper - one that's more robust, maybe with tests and such as well (ChatGPT can give you good ideas to get going here). Not everything has to be all serious, it's okay to play around sometimes, ya know! If so, feel free to make a PR; I'd be happy to have a look at it & share opinions.

# Of course...
`ffmpeg` has (since this issue) gotten a lot better at HDR->SDR, including via. GPUs (which, honestly, a lot of CPUs come with in a perfectly passable quality for this kind of image processing). This also brings the decode/encode operations closer to the actual processing, minimizing copies and so on.

So yeah. For serious practical use cases, I highly suggest just trying to configure `ffmpeg`; not least because this little program will most happily eat every single CPU cycle on every single core! With that said, `ffmpeg` does often come with its own demons; in constrast, `fast-hdr` is almost annoyingly simple.

**Comment by so-rose** [comment]
Going to close this for now. Feel free to reopen if there's something I missed!
